language: android

android:
  components:
    - tools
    - platform-tools
    - android-25
    - build-tools-25.0.2
    - extra-android-m2repository

jdk:
  - oraclejdk8

script:
  - ./gradlew clean check
